---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'


platforms:
  - name: ubuntu-12.04
    driver:
      vagrantfile_erb: Vagrantfile.erb

  #- name: ubuntu-14.04
  #- name: centos-6.4
  - name: centos-6.5
    driver:
      vagrantfile_erb: Vagrantfile.erb


suites:
  - name: zabbix-server-test
    run_list:
      - recipe[timezone-ii]
      - recipe[apt]
      - recipe[yum]     
      - recipe[mysql::client]
      - recipe[apache2]
      - recipe[apache2::mod_php5]
      - recipe[build-essential]
      - recipe[database::mysql]
      - recipe[mysql::server]
      - recipe[zabbix]
      - recipe[zabbix::database]
      - recipe[zabbix::server]
      - recipe[zabbix::web]
    attributes:
      ubuntu:
        mirror_site_url: http://ftp.jaist.ac.jp/pub/Linux/ubuntu/
        version: "12.04"
        need_deb_src: false
        need_update: true
      tz: "Asia/Tokyo"
      mysql:
        "server_root_password": "ilovethispassword"
        "server_repl_password": "ilovethispassword"
        "server_debian_password": "ilovethispassword"
      zabbix:
        agent:
          checksum: "1d5b62790c04966944f09bb629cbdc2749f8767b5da7d246fce6aab1397741bd"
          branch: "ZABBIX%20Latest%20Stable"
          version: "2.2.5"
          source_url: null
          install: true
          install_method: prebuild
          servers:
            - localhost
        server:
          branch: "ZABBIX%20Latest%20Stable"
          version: "2.2.5"
          source_url: null
          install: true
          install_method: source
          db_install_method: mysql
          dbname: "zabbix"
          dbuser: "zabbix" 
          dbhost: "localhost"
          dbpassword: "ilovethispassword"
          dbport: "3306"
          configure_options:
            - "--with-libcurl"
            - "--with-net-snmp"
            - "--with-mysql"
        web:
          install: true
          fqdn: localhost
          install_method: "apache"
          user: "apache"
          php:
            settings:
              date.timezone: "'Asia/Tokyo'"
        database:
          dbpassword: "ilovethispassword"
 
