---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'


platforms:
  #- name: ubuntu-12.04
  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    run_list:
      - recipe[zabbix-server-test::change-apt]
      #- recipe[ubuntu-change-source-list]
      #- recipe[apt]
    attributes:
      apt:
        compile_time_update: true
      build-essential:
        compile_time: true
      ubuntu:
        mirror_site_url: "http://ftp.jaist.ac.jp/pub/Linux/ubuntu/"
        version: "14.04"
        need_deb_src: false
        need_update: true
  #- name: ubuntu-14.04
  #- name: centos-6.4
  #- name: centos-6.5
  - name: centos-7.0
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    run_list:
      - recipe[yum]
      - recipe[yum-mysql-community::mysql56]
    attributes:
      yum:
        main:
          keepcache:  True
        mysql56-community:
          repositoryid: "mysql-5.6-community"
          description: "MySQL 5.6 Community Server"
          baseurl: "http://repo.mysql.com/yum/mysql-5.6-community/el/$releasever/$basearch/"
          gpgkey: "https://raw.githubusercontent.com/rs-services/equinix-public/master/cookbooks/db_mysql/files/centos/mysql_pubkey.asc"
          failovermethod: "priority"
          gpgcheck: true
          enabled: true


suites:
  - name: default
    run_list:
      - recipe[timezone-ii]
      - recipe[mysql::client]
      - recipe[apache2]
      - recipe[apache2::mod_php5]
      - recipe[apache2::mod_rewrite]
      - recipe[build-essential]
      - recipe[database::mysql]
      - recipe[mysql::server]
      - recipe[zabbix]
      - recipe[zabbix::database]
      - recipe[zabbix::server]
      - recipe[zabbix::web]
      - recipe[zabbix-server-test::apache_setting]
    attributes:
      tz: "Asia/Tokyo"
      mysql:
        "bind_address": "0.0.0.0"
        "server_root_password": "ilovethispassword"
        "server_repl_password": "ilovethispassword"
        "server_debian_password": "ilovethispassword"
      zabbix:
        agent:
          hostname: "localhost"
          checksum: "1d5b62790c04966944f09bb629cbdc2749f8767b5da7d246fce6aab1397741bd"
          branch: "ZABBIX%20Latest%20Stable"
          version: "2.2.5"
          source_url: null
          install: true
          install_method: prebuild
          servers:
            - localhost
        server:
          branch: "ZABBIX%20Latest%20Stable"
          version: "2.2.5"
          source_url: null
          install: true
          install_method: source
          db_install_method: mysql
          dbname: "zabbix"
          dbuser: "zabbix"
          dbhost: "localhost"
          dbpassword: "ilovethispassword"
          dbport: "3306"
          configure_options:
            - "--with-libcurl"
            - "--with-net-snmp"
            - "--with-mysql"
        web:
          install: true
          fqdn: localhost
          install_method: "apache"
          user: "apache"
          php:
            settings:
              date.timezone: "'Asia/Tokyo'"
        database:
          dbpassword: "ilovethispassword"
